Repository SHARE-PLATE/frontend, pull requests merged in 2022-08, with the labels that each got.

#15 [JinJeon] carousel, ads 컴포넌트 구현
  package-lock.json
  package.json
  src/components/Ads/Ads.style.tsx
  src/components/Ads/index.tsx
  src/components/Carousel/Carousel.style.tsx
  src/components/Carousel/index.tsx
  src/components/Header/index.tsx
  src/components/LoginButton/index.tsx
  src/components/SideBar/index.tsx
  src/components/SideBar/sidebarContentsInfo.ts
  src/constants/mentions.ts
  src/constants/words.ts
  src/pages/Main/index.tsx
  src/query/mediaQuery.tsx
  src/styles/GlobalStyle.tsx
Labels: JinJeon, Feature

#17 [Khan] 주소 검색 API 생성
  .gitignore
  src/components/SideBar/index.tsx
  src/store/location.ts
  src/utils/getLocation.ts
Labels: Khan, Feature

#20 [JinJeon] carousel 스타일 변경
  src/components/Ads/Ads.style.tsx
  src/components/Ads/index.tsx
  src/components/Carousel/Carousel.style.tsx
  src/components/Carousel/index.tsx
Labels: JinJeon, Style

#23 [JinJeon] 네비게이션 바 기능 구현 및 검색창 기능 임시 생성
  src/App.tsx
  src/components/NavigationBar/NavigationBar.style.tsx
  src/components/NavigationBar/index.tsx
  src/components/Portal/Portal.style.tsx
  src/components/Portal/index.tsx
  src/components/Search/Search.style.tsx
  src/components/Search/index.tsx
  src/components/SideBar/index.tsx
  src/query/mediaQuery.tsx
  src/store/portal.ts
Labels: JinJeon, Feature

#25 [JinJeon] 최근검색어 등록 ∙ 삭제 기능 구현 및 쉐어 등록 버튼 생성
  package-lock.json
  package.json
  src/App.tsx
  src/assets/icons/form.svg
  src/assets/icons/index.tsx
  src/components/NavigationBar/NavigationBar.style.tsx
  src/components/NavigationBar/index.tsx
  src/components/Portal/Portal.style.tsx
  src/components/Portal/index.tsx
  src/components/Search/Search.style.tsx
  src/components/Search/index.tsx
  src/components/SearchRecent/SearchRecent.style.tsx
  src/components/SearchRecent/index.tsx
  src/components/ShareFormButton/ShareFormButton.style.tsx
  src/components/ShareFormButton/index.tsx
  src/constants/mentions.ts
  src/constants/words.ts
  src/store/localStorage.ts
  src/type/PortalType.ts
  src/utils/getTime.ts
  src/utils/useLocalStorage.ts
Labels: JinJeon, Feature

#26 [Khan] 정렬 기능 구현
  src/components/CategoryButton/index.tsx
  src/components/PreviewShareList/index.tsx
  src/components/common/PersonnelStatus/index.tsx
  src/constants/category.ts
  src/data/shareList.ts
  src/pages/ShareList/index.tsx
  src/store/shareList.ts
  src/utils/ShareListSort.ts
Labels: Khan, Feature

#32 [JinJeon] 공통 스타일 설정 및 일부 스타일 수정
  public/index.html
  src/assets/icons/index.tsx
  src/assets/icons/kakao.svg
  src/assets/icons/sharePlate.svg
  src/components/Carousel/Carousel.style.tsx
  src/components/Carousel/index.tsx
  src/components/NavigationBar/NavigationBar.style.tsx
  src/components/NavigationBar/index.tsx
  src/components/Portal/Portal.style.tsx
  src/components/Search/Search.style.tsx
  src/components/Search/index.tsx
  src/components/SearchPopular/SearchPopular.style.tsx
  src/components/SearchRecent/SearchRecent.style.tsx
  src/components/ShareFormButton/ShareFormButton.style.tsx
  src/components/ShareFormButton/index.tsx
  src/components/common/PersonnelStatus/index.tsx
  src/styles/GlobalStyle.tsx
  src/styles/animations.css
  src/styles/theme.tsx
Labels: JinJeon, Refactor, Style

#33 [Khan] 프로필 페이지 레이아웃 완성
  src/components/MainHeader/MainHeader.style.ts
  src/components/MainHeader/index.tsx
  src/components/MyMenu/index.tsx
  src/components/PreviewShareListCenterImage/index.tsx
  src/components/PreviewShareListLeftImage/PreviewShareListLeftImage.style.ts
  src/components/PreviewShareListLeftImage/index.tsx
  src/components/ReserveShare/index.tsx
  src/components/UserMenu/index.tsx
  src/components/common/PersonnelStatus/index.tsx
  src/components/common/Title/index.tsx
  src/constants/userMenu.ts
  src/data/shareList.ts
  src/data/sharing.ts
  src/pages/Main/index.tsx
  src/pages/Profile/index.tsx
  src/pages/ShareList/index.tsx
Labels: Khan, Feature

#41 [JinJeon] PR(#37) Merge Error 수정
  src/App.tsx
  src/assets/icons/user.svg
  src/components/Ads/index.tsx
  src/components/Carousel/Carousel.style.tsx
  src/components/Carousel/index.tsx
  src/components/Login/Login.style.tsx
  src/components/Login/index.tsx
  src/components/LoginButton/index.tsx
  src/components/MyMenu/MyMenu.style.tsx
  src/components/MyMenu/index.tsx
  src/components/NavigationBar/NavigationBar.style.tsx
  src/components/NavigationBar/index.tsx
  src/components/Portal/Portal.style.tsx
  src/components/Portal/index.tsx
  src/components/PreviewShareListCenterImage/PreviewShareListCenterImage.style.tsx
  src/components/PreviewShareListCenterImage/index.tsx
  src/components/ProfileHeader/ProfileHeader.style.tsx
  src/components/ProfileHeader/index.tsx
  src/components/ReserveShare/index.tsx
  src/components/Search/index.tsx
  src/components/SearchPopular/SearchPopular.style.tsx
  src/components/ShareFormButton/index.tsx
  src/components/SideBar/index.tsx
  src/components/UserInfo/UserInfo.style.tsx
  src/components/UserInfo/index.tsx
  src/components/UserMenu/UserMenu.style.tsx
  src/components/UserMenu/index.tsx
  src/components/common/PersonnelStatus/index.tsx
  src/components/common/Title/Title.style.tsx
  src/components/common/Title/index.tsx
  src/constants/mentions.ts
  src/pages/Profile/Profile.style.tsx
  src/pages/Profile/index.tsx
  src/router/index.tsx
  src/store/portal.ts
  src/styles/GlobalStyle.tsx
  src/styles/mixin.ts
Labels: Fix

#44 [Khan] 쉐어 리스트 페이지 배달쉐어 레이아웃
  src/components/CategoryButton/CategoryButton.tsyle.ts
  src/components/CategoryButton/index.tsx
  src/components/PreviewShareListBigSizeImage/PreviewShareListBigSizeImage.style.ts
  src/components/PreviewShareListBigSizeImage/index.tsx
  src/components/PreviewShareListLeftImage/PreviewShareListLeftImage.style.ts
  src/components/PreviewShareListLeftImage/index.tsx
  src/components/RemainedTime/RemainedTime.style.tsx
  src/components/ShareListHeader/ShareListHeader.style.ts
  src/components/Tabs/Tabs.styled.ts
  src/components/Tabs/index.tsx
  src/components/common/Button/Button.style.ts
  src/components/common/Button/index.tsx
  src/data/shareList.ts
  src/pages/ShareList/ShareList.style.ts
  src/pages/ShareList/index.tsx
  src/store/filterShareList.ts
  src/store/shareList.ts
  src/utils/ShareListSort.ts
  src/utils/getTimeDiff.ts
Labels: Khan, Feature

#46 [JinJeon] stylelint 적용
  .stylelintrc
  package-lock.json
  package.json
  src/components/Address/Address.style.tsx
  src/components/Ads/Ads.style.tsx
  src/components/Carousel/Carousel.style.tsx
  src/components/Login/Login.style.tsx
  src/components/LoginButton/LoginButton.style.tsx
  src/components/MainHeader/MainHeader.style.tsx
  src/components/ModalContainer/ModalContainer.style.ts
  src/components/MyMenu/MyMenu.style.tsx
  src/components/NavigationBar/NavigationBar.style.tsx
  src/components/Portal/Portal.style.tsx
  src/components/PreviewShareList/PreviewShareList.style.ts
  src/components/PreviewShareList/index.tsx
  src/components/PreviewShareListBigSizeImage/PreviewShareListBigSizeImage.style.ts
  src/components/PreviewShareListCenterImage/PreviewShareListCenterImage.style.tsx
  src/components/PreviewShareListLeftImage/PreviewShareListLeftImage.style.ts
  src/components/PreviewShareListLongImage/PreviewShareListLongImage.style.tsx
  src/components/RemainedTime/RemainedTime.style.tsx
  src/components/Search/Search.style.tsx
  src/components/SearchPopular/SearchPopular.style.tsx
  src/components/SearchRecent/SearchRecent.style.tsx
  src/components/ShareFormButton/ShareFormButton.style.tsx
  src/components/ShareListItemLongImage/ShareListItemLongImage.style.tsx
  src/components/SideBar/Sidebar.style.tsx
  src/components/Tabs/Tabs.styled.ts
  src/components/UserInfo/UserInfo.style.tsx
  src/components/UserMenu/UserMenu.style.tsx
  src/components/common/Button/Button.style.ts
  src/components/common/Modal/Modal.style.ts
  src/components/common/PersonnelStatus/index.tsx
  src/components/common/Title/Title.style.tsx
  src/pages/Main/Main.style.tsx
  src/pages/Profile/Profile.style.tsx
  src/pages/ShareList/ShareList.style.ts
  src/styles/GlobalStyle.tsx
  src/styles/Reset.tsx
  src/styles/mixin.ts
Labels: JinJeon, Style, Chore

#48 [JinJeon] 메인 페이지 배달 ∙ 재료 쉐어 리스트 및 로그인 화면 구성
  .eslintrc.json
  src/components/Login/Login.style.tsx
  src/components/LoginArea/LoginArea.style.tsx
  src/components/LoginArea/index.tsx
  src/components/MainContents/MainContents.style.tsx
  src/components/MainContents/index.tsx
  src/components/NavigationBar/NavigationBar.style.tsx
  src/components/NavigationBar/index.tsx
  src/components/Portal/Portal.style.tsx
  src/components/PreviewShareListLeftImage/PreviewShareListLeftImage.style.ts
  src/components/PreviewShareListLeftImage/index.tsx
  src/components/PreviewShareListLongImage/PreviewShareListLongImage.style.tsx
  src/components/RemainedTime/RemainedTime.style.tsx
  src/components/Search/Search.style.tsx
  src/components/Search/index.tsx
  src/components/SearchRecent/SearchRecent.style.tsx
  src/components/SideBar/index.tsx
  src/constants/mentions.ts
  src/constants/words.ts
  src/pages/Main/index.tsx
  src/styles/mixin.ts
Labels: JinJeon, Feature, Refactor, Style

#51 [Khan] 반응형으로 변경
  src/pages/ShareList/ShareList.style.ts
Labels: Khan, Feature, Refactor

#52 [Khan] 배달쉐어 상단 레이아웃
  src/components/PreviewShareListBigSizeImage/index.tsx
  src/components/PreviewShareListLeftImage/index.tsx
  src/components/RemainedTime/RemainedTime.style.tsx
  src/components/RemainedTime/index.tsx
  src/components/ShareDetailContents/ShareDetailContents.style.ts
  src/components/ShareDetailContents/index.tsx
  src/components/ShareDetailImage/ShareDetailImage.style.ts
  src/components/ShareDetailImage/index.tsx
  src/components/SideBar/SideBar.style.ts
  src/components/SideBar/SideBarContents.ts
  src/components/SideBar/index.tsx
  src/components/common/Icon/constants.ts
  src/data/detail.ts
  src/pages/ShareDetail/index.tsx
  src/router/index.tsx
Labels: Khan, Feature

#56 [JinJeon] 전체 페이지 및 쉐어 목록 페이지 스타일링
  src/assets/icons/chevronDown.svg
  src/assets/icons/index.tsx
  src/components/Address/Address.style.tsx
  src/components/Address/index.tsx
  src/components/CategoryButton/CategoryButton.tsyle.ts
  src/components/CategoryButton/index.tsx
  src/components/MainHeader/MainHeader.style.tsx
  src/components/MainHeader/index.tsx
  src/components/PreviewShareListBigSizeImage/PreviewShareListBigSizeImage.style.ts
  src/components/PreviewShareListBigSizeImage/index.tsx
  src/components/PreviewShareListCenterImage/PreviewShareListCenterImage.style.tsx
  src/components/PreviewShareListLongImage/PreviewShareListLongImage.style.tsx
  src/components/ProfileHeader/ProfileHeader.style.tsx
  src/components/SearchRecent/SearchRecent.style.tsx
  src/components/ShareFormButton/ShareFormButton.style.tsx
  src/components/ShareListHeader/index.tsx
  src/components/ShareListItemHalfImage/ShareListItemHalfImage.style.tsx
  src/components/ShareListItemLongImage/ShareListItemLongImage.style.tsx
  src/components/Tabs/Tabs.styled.ts
  src/components/Tabs/Tabs.styled.tsx
  src/components/Tabs/index.tsx
  src/components/UserInfo/UserInfo.style.tsx
  src/components/UserMenu/UserMenu.style.tsx
  src/components/UserMenu/index.tsx
  src/components/common/Button/Button.style.ts
  src/components/common/Button/index.tsx
  src/components/common/Icon/Icon.style.ts
  src/data/shareList.ts
  src/pages/Main/Main.style.tsx
  src/pages/Main/index.tsx
  src/pages/ShareList/ShareList.style.tsx
  src/pages/ShareList/index.tsx
  src/store/filterShareList.ts
  src/styles/mixin.ts
Labels: JinJeon, Refactor, Style

#57 [Khan] 데이터 recoil로 변경
  package-lock.json
  package.json
  src/api/shareList.ts
  src/components/Tabs/index.tsx
  src/constants/api.ts
  src/hooks/useGeolocation.tsx
  src/pages/ShareList/index.tsx
  src/setupProxy.js
  src/store/filterShareList.ts
  src/store/location.ts
  src/store/shareList.ts
  src/utils/ShareListSort.ts
Labels: Khan, Feature, Refactor

#60 [Khan] 쉐어 모집 페이지 기능 구현 완료
  src/api/shareList.ts
  src/assets/icons/camera.svg
  src/assets/icons/index.tsx
  src/components/FileRegistrationFailedModal/FileRegistrationFailedModal.style.ts
  src/components/FileRegistrationFailedModal/index.tsx
  src/components/ModalContainer/AddressModal.tsx
  src/components/ModalContainer/ModalContainer.style.ts
  src/components/ShareForm/ContentDescription.tsx
  src/components/ShareForm/FileContainer.tsx
  src/components/ShareForm/ShareForm.style.ts
  src/components/ShareForm/TextContainer.tsx
  src/components/ShareForm/index.tsx
  src/components/ShareFormButton/ShareFormButton.style.tsx
  src/components/ShareFormButton/index.tsx
  src/components/ShareFormHeader/ShareFormHeader.style.ts
  src/components/ShareFormHeader/index.tsx
  src/components/common/InputForm/InputForm.style.ts
  src/components/common/InputForm/index.tsx
  src/components/common/Modal/Modal.style.ts
  src/components/common/Modal/index.tsx
  src/constants/api.ts
  src/constants/pathName.ts
  src/hooks/useInput.tsx
  src/pages/ShareForm/index.tsx
  src/pages/ShareRegistration/ShareRegistration.style.ts
  src/pages/ShareRegistration/index.tsx
  src/router/index.tsx
Labels: Khan, Feature

#64 [Khan] 목 데이터 서버 데이터로 변경
  src/api/shareRecommended.ts
  src/components/Advertisement/Advertisement.style.tsx
  src/components/Advertisement/index.tsx
  src/components/MainContents/index.tsx
  src/components/PreviewShareList/index.tsx
  src/components/PreviewShareListBigSizeImage/index.tsx
  src/components/PreviewShareListHalfImage/index.tsx
  src/components/PreviewShareListLeftImage/PreviewShareListLeftImage.style.ts
  src/components/PreviewShareListLeftImage/index.tsx
  src/components/PreviewShareListLongImage/PreviewShareListLongImage.style.tsx
  src/components/PreviewShareListLongImage/index.tsx
  src/components/ShareDetailHeader/ShareDetailHeader.style.ts
  src/components/ShareDetailHeader/index.tsx
  src/components/ShareDetailInfo/ShareDetailInfo.style.ts
  src/components/ShareDetailInfo/index.tsx
  src/components/ShareListItemHalfImage/ShareListItemHalfImage.style.tsx
  src/components/ShareListItemHalfImage/index.tsx
  src/components/ShareListItemLongImage/ShareListItemLongImage.style.tsx
  src/components/ShareListItemLongImage/index.tsx
  src/components/UserInfoWithFollow/index.tsx
  src/constants/api.ts
  src/data/shareList.ts
  src/pages/Main/index.tsx
  src/pages/ShareDetail/index.tsx
  src/type/shareList.ts
  src/utils/ShareListSort.ts
Labels: Khan, Refactor, Style

#66 [JinJeon] 로그인 테스트를 위한 배포
  .github/workflows/deploy.yml
Labels: JinJeon, Chore

#68 [JinJeon] PR(#65) Merge Error 수정
  src/api/account.ts
  src/components/BottomBar/index.tsx
  src/components/Login/index.tsx
  src/components/PreviewShareListLongImage/index.tsx
  src/components/Search/index.tsx
  src/components/SearchRecent/index.tsx
  src/constants/api.ts
  src/constants/mentions.ts
  src/constants/words.ts
  src/pages/ChattingDetail/test.tsx
  src/pages/LoginCallback/LoginCallback.style.tsx
  src/pages/LoginCallback/index.tsx
  src/pages/ShareDetail/index.tsx
  src/store/localStorage.ts
  src/store/thumbnailImageUrl.ts
  src/styles/GlobalStyle.tsx
  src/utils/LocalStorage.ts
  src/utils/localStorage.ts
Labels: JinJeon, Fix

#73 [JinJeon] 찜하기 버튼 기능 추가
  src/api/account.ts
  src/api/wish.ts
  src/components/BottomBar/index.tsx
  src/components/Chat/Chat.style.tsx
  src/components/ChattingBar/ChattingBar.style.tsx
  src/components/ChattingDetailContents/ChattingDetailContents.style.tsx
  src/components/ChattingDetailHeader/ChattingDetailHeader.style.tsx
  src/components/ChattingDetailInfo/ChattingDetailInfo.style.tsx
  src/components/FailedContents/FailedContents.style.ts
  src/components/FileRegistrationFailedModal/FileRegistrationFailedModal.style.ts
  src/components/InteractionBar/InteractionBar.style.tsx
  src/components/InteractionBar/index.tsx
  src/components/Loading/Loading.style.tsx
  src/components/ScrollToTopBtn/index.tsx
  src/components/SearchShareHeader/SearchShareHeader.style.ts
  src/components/ShareForm/ShareForm.style.ts
  src/components/ShareFormButton/ShareFormButton.style.tsx
  src/components/ShareFormHeader/ShareFormHeader.style.ts
  src/components/common/InputForm/InputForm.style.ts
  src/constants/api.ts
  src/constants/words.ts
  src/pages/ChattingDetail/ChattingDetail.style.tsx
  src/pages/LoginCallback/LoginCallback.style.tsx
  src/pages/ShareDetail/index.tsx
  src/pages/ShareRegistration/ShareRegistration.style.ts
Labels: JinJeon, Feature, Refactor

#74 [Khan] 판매내역 구매내역 페이지 구현
  src/assets/icons/checkCircle.svg
  src/assets/icons/index.tsx
  src/components/CategoryButton/CategoryButton.style.ts
  src/components/CategoryButton/index.tsx
  src/components/HistoryHeader/HistoryHeader.style.ts
  src/components/HistoryHeader/index.tsx
  src/components/MyMenu/index.tsx
  src/components/PreviewShareListLeftImage/ExpirationDate.tsx
  src/components/PreviewShareListLeftImage/ImageContainer.tsx
  src/components/PreviewShareListLeftImage/PreviewShareListLeftImage.style.ts
  src/components/PreviewShareListLeftImage/index.tsx
  src/components/Tabs/Tabs.styled.tsx
  src/components/Tabs/index.tsx
  src/constants/api.ts
  src/constants/category.ts
  src/constants/historyContent.ts
  src/constants/pathName.ts
  src/pages/History/index.tsx
  src/pages/SearchShare/index.tsx
  src/pages/ShareList/ShareList.style.tsx
  src/pages/ShareList/index.tsx
  src/router/index.tsx
  src/store/filterShareList.ts
  src/styles/mixin.ts
Labels: Khan, Feature

#76 [Khan] 내역 페이지 완성 (데이터 페치 X)
  src/components/Tabs/Tabs.styled.tsx
  src/components/Tabs/index.tsx
  src/constants/category.ts
  src/constants/historyContent.ts
  src/constants/mentions.ts
  src/pages/History/History.style.ts
  src/pages/History/index.tsx
  src/pages/ShareList/index.tsx
  src/store/filterShareList.ts
  src/utils/getMention.ts
Labels: Khan, Feature, Refactor
