Repository SHARE-PLATE/frontend, pull requests merged in 2022-07, with the labels that each got.

#3 [Khan, JinJeon] 프로젝트 초기 설정
  .eslintrc.json
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/PULL_REQUEST_TEMPLATE.md
  .gitignore
  .prettierrc
  README.md
  config-overrides.js
  package-lock.json
  package.json
  public/index.html
  public/logo192.png
  public/logo512.png
  public/manifest.json
  public/robots.txt
  src/App.css
  src/App.test.tsx
  src/App.tsx
  src/custom.d.ts
  src/index.css
  src/index.tsx
  src/logo.svg
  src/pages/Error/index.tsx
  src/pages/LoginCallback/index.tsx
  src/pages/Main/index.tsx
  src/pages/NotFound/index.tsx
  src/pages/Notice/index.tsx
  src/pages/Profile/index.tsx
  src/pages/ShareDetail/index.tsx
  src/pages/ShareForm/index.tsx
  src/pages/ShareList/index.tsx
  src/react-app-env.d.ts
  src/reportWebVitals.ts
  src/router/ProtectedRoute.tsx
  src/router/index.tsx
  src/setupTests.ts
  tsconfig.json
  tsconfig.path.json
Labels: JinJeon, Khan, Chore

#7 [Khan, JinJeon] 헤더 레이아웃
  src/App.tsx
  src/components/Address/index.tsx
  src/components/Header/Header.style.ts
  src/components/Header/index.tsx
  src/components/Modal/AddressModal.tsx
  src/hooks/useModal.tsx
Labels: JinJeon, Khan, Feature, Style

#9 [JinJeon] Portal 컴포넌트 구현 및 로그인 버튼에 적용
  public/index.html
  src/components/Header/index.tsx
  src/components/LoginButton/LoginButton.style.tsx
  src/components/LoginButton/index.tsx
  src/components/Portal/Portal.style.tsx
  src/components/Portal/index.tsx
  src/styles/GlobalStyle.tsx
Labels: JinJeon, Feature

#12 [Khan] 헤더 부분 주소창 1
  package-lock.json
  package.json
  src/components/Address/index.tsx
  src/components/Modal/AddressModal.tsx
  src/components/ModalContainer/AddressModal.tsx
  src/components/ModalContainer/ModalContainer.style.ts
  src/components/common/Modal/Modal.style.ts
  src/components/common/Modal/index.tsx
  src/constants/defaultLocation.ts
  src/hooks/useGeolocation.tsx
  src/index.tsx
  src/store/location.ts
Labels: Khan, Feature

#13 [JinJeon] sidebar 컴포넌트 생성 및 기본 렌더링 구현
  src/components/Header/index.tsx
  src/components/LoginButton/index.tsx
  src/components/Portal/Portal.style.tsx
  src/components/Portal/index.tsx
  src/components/SideBar/Sidebar.style.tsx
  src/components/SideBar/index.tsx
  src/store/portal.ts
  src/styles/GlobalStyle.tsx
Labels: JinJeon, Feature
