Repository SHARE-PLATE/frontend, pull requests merged in 2022-10, with the labels that each got.

#117 [Khan] 찜하기 삭제 및 키워드 에러 수정
  src/assets/icons/hamburger.svg
  src/assets/icons/heart.svg
  src/assets/icons/map.svg
  src/components/AddKeyWordButton/AddKeyWordButton.style.ts
  src/components/Address/index.tsx
  src/components/AddressDetail/AddressDetail.style.tsx
  src/components/AddressList/AddressList.style.tsx
  src/components/AddressListItem/AddressListItem.style.tsx
  src/components/AddressMap/AddressMap.style.ts
  src/components/AddressPortal/AddressPortal.style.tsx
  src/components/ChatroomBar/ChatroomBar.style.tsx
  src/components/ChatroomDetailHeader/ChatroomDetailHeader.style.tsx
  src/components/ExpirationDate/ExpirationDate.style.ts
  src/components/FailedContents/FailedContents.style.ts
  src/components/FailedContents/index.tsx
  src/components/HomeLogin/HomeLogin.style.tsx
  src/components/KeywordAddressListItem/KeywordAddressListItem.style.ts
  src/components/KeywordAddressListItem/index.tsx
  src/components/KeywordAddressPortal/KeywordAddressPortal.style.ts
  src/components/KeywordAddressPortal/index.tsx
  src/components/LoginPortal/LoginPortal.style.tsx
  src/components/MainHeader/MainHeader.style.tsx
  src/components/MainHeader/index.tsx
  src/components/MapArea/MapArea.style.ts
  src/components/MyMenu/index.tsx
  src/components/NavigationBar/NavigationBar.style.tsx
  src/components/NavigationBar/index.tsx
  src/components/NoticeContent/NoticeContent.style.tsx
  src/components/PreviewShareListBigSizeImage/PreviewShareListBigSizeImage.style.ts
  src/components/PreviewShareListBigSizeImage/index.tsx
  src/components/PreviewShareListHalfImage/PreviewShareListHalfImage.style.tsx
  src/components/PreviewShareListHalfImage/index.tsx
  src/components/PreviewShareListLeftImage/PreviewShareListLeftImage.style.ts
  src/components/RegisteredKeyword/index.tsx
  src/components/RemainedTime/RemainedTime.style.tsx
  src/components/ScrollToTopBtn/ScrollToTopBtn.style.tsx
  src/components/ShareDetailHeader/ShareDetailHeader.style.ts
  src/components/ShareDetailInfo/ShareDetailInfo.style.ts
  src/components/ShareListItemLongImage/ShareListItemLongImage.style.tsx
  src/components/ShareMapHeader/index.tsx
  src/components/ShareSearchHeader/index.tsx
  src/components/SuggestedSearchTerms/index.tsx
  src/components/UserInfo/UserInfo.style.tsx
  src/components/UserInfoWithFollow/UserInfoWithFollow.style.tsx
  src/components/WishHeart/WishHeart.style.ts
  src/components/WishHeart/index.tsx
  src/components/common/Icon/Icon.style.ts
  src/components/common/ImageContents/index.tsx
  src/components/common/PersonnelStatus/PersonnelStatus.style.tsx
  src/components/common/Title/Title.style.tsx
  src/pages/AddKeyword/index.tsx
  src/pages/Chatrooms/Chatrooms.style.tsx
  src/pages/History/index.tsx
  src/pages/Notice/Notice.style.tsx
  src/pages/Profile/index.tsx
  src/pages/WishList/index.tsx
  src/store/shareList.ts
  src/styles/theme.tsx
  src/type/keyword.ts
Labels: Khan, Feature, Style, Fix

#120 [Khan] 내 주변 지도 에러 수정
  src/components/MapArea/MapArea.style.ts
  src/components/MapArea/ShareListMarker.tsx
  src/components/MapArea/ShareListSlide.tsx
  src/components/MapArea/index.tsx
  src/components/ShareForm/FileContainer/index.tsx
  src/components/ShareMapHeader/index.tsx
  src/constants/words.ts
  src/pages/ShareMap/ShareMap.style.ts
  src/pages/ShareRegistration/index.tsx
  src/store/shareMap.ts
  src/type/shareList.ts
Labels: Khan, Feature, Fix

#124 [JinJeon] 쉐어 지도 페이지 디자인 수정 및 기능 완성
  src/api/shareList.ts
  src/assets/icons/index.tsx
  src/assets/icons/refresh.svg
  src/assets/icons/target.svg
  src/components/AddressRegistered/index.tsx
  src/components/Loading/Loading.style.tsx
  src/components/MainHeader/MainHeader.style.tsx
  src/components/MapArea/MapArea.style.ts
  src/components/MapArea/ShareListSlide.tsx
  src/components/MapArea/index.tsx
  src/components/PreviewShareListBigSizeImage/PreviewShareListBigSizeImage.style.ts
  src/components/PreviewShareListBigSizeImage/index.tsx
  src/components/PreviewShareListLeftImage/PreviewShareListLeftImage.style.ts
  src/components/PreviewShareListLeftImage/index.tsx
  src/components/ShareListSlide/ShareListSlide.style.tsx
  src/components/ShareListSlide/index.tsx
  src/components/ShareMapArea/CurrentLocationMarker.tsx
  src/components/ShareMapArea/ShareListMarker.tsx
  src/components/ShareMapArea/ShareMapArea.style.tsx
  src/components/ShareMapArea/index.tsx
  src/components/ShareMapHeader/index.tsx
  src/components/common/ImgContainer/ImgContainer.style.tsx
  src/components/common/ImgContainer/index.tsx
  src/constants/words.ts
  src/hooks/useGeolocation.tsx
  src/pages/ShareList/index.tsx
  src/pages/ShareMap/ShareMap.style.ts
  src/pages/ShareMap/index.tsx
  src/store/filterShareList.ts
  src/store/location.ts
  src/store/shareList.ts
  src/store/shareMap.ts
  src/styles/animations.css
  src/utils/ShareListSort.ts
  src/utils/getLocation.ts
Labels: JinJeon, Feature, Refactor, Style

#123 [Khan] 프로필 수정 페이지 레이아웃
  src/assets/icons/index.tsx
  src/assets/icons/logout.svg
  src/assets/icons/purchaseHistoryBlack.svg
  src/assets/icons/salesHistoryBlack.svg
  src/components/EditUserInfoFrom/EditUserInfoFrom.style.ts
  src/components/EditUserInfoFrom/index.tsx
  src/components/EditUserInfoHeader/EditUserInfoHeader.style.ts
  src/components/EditUserInfoHeader/index.tsx
  src/components/KebabMenu/KebabMenu.style.ts
  src/components/KebabMenu/index.tsx
  src/components/KebabMenuModal/index.tsx
  src/components/KeywordBox/index.tsx
  src/components/NavigationBar/index.tsx
  src/components/PreviewShareListLeftImage/PreviewShareListLeftImage.style.ts
  src/components/PreviewShareListLeftImage/index.tsx
  src/components/ToastModal/ToastModal.style.ts
  src/components/ToastModal/index.tsx
  src/components/UserInfo/UserInfo.style.tsx
  src/components/UserInfo/index.tsx
  src/components/UserMenu/index.tsx
  src/components/common/BackTitleHeader/BackTitleHeader.style.ts
  src/components/common/InputForm/InputForm.style.ts
  src/components/common/SelectModal/index.tsx
  src/constants/pathName.ts
  src/constants/userMenu.ts
  src/constants/words.ts
  src/pages/EditUserInfo/EditUserInfo.style.ts
  src/pages/EditUserInfo/index.tsx
  src/pages/History/index.tsx
  src/pages/Keyword/index.tsx
  src/pages/Profile/index.tsx
  src/pages/SettingProfile/SettingProfile.style.ts
  src/pages/SettingProfile/index.tsx
  src/router/index.tsx
  src/store/userInfo.ts
Labels: Khan, Feature

#131 [Khan] 메인페이지 검색 및 검색페이지 키워드 추가
  src/assets/icons/index.tsx
  src/assets/icons/noticeFill.svg
  src/assets/icons/searchThick.svg
  src/components/Carousel/index.tsx
  src/components/RegisteredKeyword/index.tsx
  src/components/SuggestedSearchTerms/SuggestedSearchTerms.style.ts
  src/components/SuggestedSearchTerms/index.tsx
  src/pages/AddKeyword/index.tsx
  src/pages/ShareSearch/ShareSearch.style.ts
  src/pages/ShareSearch/index.tsx
  src/portals/SearchPortal/index.tsx
  src/store/keyword.ts
  src/utils/getLocation.ts
Labels: Khan, Feature

#132 [JinJeon] 알림 페이지 기능 완성
  src/App.tsx
  src/api/keyword.ts
  src/api/notice.ts
  src/api/shareList.ts
  src/assets/icons/editingCamera.svg
  src/assets/icons/index.tsx
  src/components/BottomMessage/BottomMessage.style.tsx
  src/components/BottomMessage/index.tsx
  src/components/Chat/index.tsx
  src/components/ChatroomBar/ChatroomBar.style.tsx
  src/components/ChatroomBar/index.tsx
  src/components/ChatroomDetailContents/ChatroomDetailContents.style.tsx
  src/components/ChatroomDetailContents/index.tsx
  src/components/ChatroomsItem/index.tsx
  src/components/EditUserInfoForm/EditUserInfoForm.style.ts
  src/components/EditUserInfoForm/index.tsx
  src/components/EditUserInfoHeader/EditUserInfoHeader.style.ts
  src/components/EditUserInfoHeader/index.tsx
  src/components/NoticeActivity/NoticeActivity.style.tsx
  src/components/NoticeActivity/index.tsx
  src/components/NoticeContent/NoticeContent.style.tsx
  src/components/NoticeContent/data.ts
  src/components/NoticeContent/index.tsx
  src/components/NoticeDeleteAllButton/NoticeDeleteAllButton.style.tsx
  src/components/NoticeDeleteAllButton/index.tsx
  src/components/NoticeDeleteBtn/NoticeDeleteBtn.style.tsx
  src/components/NoticeDeleteBtn/index.tsx
  src/components/NoticeDeleteModeButton/NoticeDeleteModeButton.style.tsx
  src/components/NoticeDeleteModeButton/index.tsx
  src/components/NoticeKeyword/NoticeKeyword.style.tsx
  src/components/NoticeKeyword/index.tsx
  src/components/UserMenu/UserMenu.style.tsx
  src/components/common/ImgContainer/ImgContainer.style.tsx
  src/components/common/ImgContainer/index.tsx
  src/constants/mentions.ts
  src/constants/words.ts
  src/hooks/useNoticeAlarm.tsx
  src/pages/ChatroomDetail/ChatroomDetail.style.tsx
  src/pages/ChatroomDetail/index.tsx
  src/pages/EditUserInfo/index.tsx
  src/pages/Main/Main.style.tsx
  src/pages/Notice/Notice.style.tsx
  src/pages/Notice/index.tsx
  src/pages/Profile/Profile.style.tsx
  src/portals/OptionPortal/index.tsx
  src/socket/noticeSocket.ts
  src/store/activeNotice.ts
  src/store/bottomMessage.ts
  src/store/notice.ts
  src/type/notice.ts
Labels: JinJeon, Refactor, Style

#135 [Khan] 버튼 삭제 여부 확인
  src/components/RegisteredKeyword/index.tsx
  src/pages/AddKeyword/index.tsx
  src/pages/ShareSearch/ShareSearch.style.ts
  src/pages/ShareSearch/index.tsx
  src/utils/getLocation.ts
Labels: Khan, Refactor, Fix

#136 [JinJeon] 소켓 리펙토링 및 관련 기능 재설정
  src/App.tsx
  src/api/chat.ts
  src/assets/icons/index.tsx
  src/assets/icons/warning.svg
  src/components/ChatroomBar/ChatroomBar.style.tsx
  src/components/ChatroomBar/index.tsx
  src/components/ChatroomDetailContents/ChatroomDetailContents.style.tsx
  src/components/ChatroomDetailContents/index.tsx
  src/components/ChatroomDetailHeader/ChatroomDetailHeader.style.tsx
  src/components/ChatroomsContent/ChatroomsContent.style.tsx
  src/components/ChatroomsContent/index.tsx
  src/components/ChatroomsItem/index.tsx
  src/components/NoticeActivity/NoticeActivity.style.tsx
  src/components/NoticeActivity/NoticeActivityItem/NoticeActivityItem.style.tsx
  src/components/NoticeActivity/NoticeActivityItem/index.tsx
  src/components/NoticeActivity/index.tsx
  src/components/NoticeDeleteBtn/index.tsx
  src/components/NoticeKeyword/NoticeKeyword.style.tsx
  src/components/NoticeKeyword/NoticeKeywordItem/NoticeKeywordItem.style.tsx
  src/components/NoticeKeyword/NoticeKeywordItem/index.tsx
  src/components/NoticeKeyword/index.tsx
  src/components/TopFixedWarning/TopFixedWarning.style.tsx
  src/components/TopFixedWarning/index.tsx
  src/components/common/Icon/index.tsx
  src/constants/mentions.ts
  src/hooks/useChatAlarm.tsx
  src/hooks/useNoticeAlarm.tsx
  src/hooks/useTimeout.tsx
  src/pages/ChatroomDetail/ChatroomDetail.style.tsx
  src/pages/ChatroomDetail/index.tsx
  src/pages/Chatrooms/Chatrooms.style.tsx
  src/pages/Chatrooms/index.tsx
  src/socket/chatroomSocket.ts
  src/socket/noticeSocket.ts
  src/socket/stomp.ts
  src/socket/useConnectSocket.tsx
  src/store/chatrooms.ts
  src/store/socket.ts
  src/type/chat.ts
  src/type/notice.ts
Labels: JinJeon, Feature, Refactor
